### PR TITLE
feat: allow longer function declaration lines

### PR DESCRIPTION
**Pull request by jthomerson**

### CODE REVIEW

**Comment by jthomerson** [comment]
@jimjenkins5 @lukelafountaine @pbredenberg @yokuze @onebytegone I'm curious your thoughts on this. It came from a suggestion @onebytegone saw when reviewing some of my TypeScript code. With TS, many function declarations end up being very long because of the types for each parameter, return type, and possible generics. I personally hate the weird alignment and vertical wasted space of wrapping the function declaration, so tended to just make it one long line and then add `// eslint-disable-line max-len` to the end of the line.

I just don't feel like it's critical to be able to see all the parameters and types when I'm writing the function code - I can look once (even if that involves a scroll) and then proceed from there, especially with autocomplete.

Some contrived example to demonstrate the difference:

```ts
findPets(
   ownerPartialName: string
   type?: PetTypeEnum,
   lastVisit?: Date
   sort?: PetSearchSortOrderEnum
): PetSearchResults {
   // now my code starts here at this indentation
   const searchParams = ...
}
```

Vs:

```ts
findPets(ownerPartialName: string type?: PetTypeEnum, lastVisit?: Date sort?: PetSearchSortOrderEnum): PetSearchResults {
   // now my code starts here at this indentation
   const searchParams = ...
}
```

Okay, that wasn't quite 130 chars, but still demonstrates the point. I find the one-line version infinitely more readable and appreciate that it doesn't waste all my vertical space.

Thoughts?

**Comment by jthomerson** [comment]
Oh, I forgot to mention: this PR would need some work ... I think my pattern is way too simple. We wouldn't want comments that have the word "function" in them to not have the max-len rule applied. It's just a placeholder for discussion. If you have thoughts on what the pattern should look like, please include those as well.

**Comment by onebytegone** [comment]
Lack of vertical space? Could always go with a [vertical ultrawide monitor](https://twitter.com/amirrajan/status/1230003860363673600) 😉

As for a practical response, I'm okay with either option (assuming we change our linting to support longer declarations). However, I lean towards the wrapped declaration as scrolling horizontally can become painful depending on platform, editor, and HID setup. Additionally, I think wrapped looks a little nicer when there are defaults provided for the args. For example:

```ts
function findPets(
   ownerPartialName: string,
   type?: PetTypeEnum,
   lastVisit?: Date,
   sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending,
   ignoreCache: boolean = false
): PetSearchResults {
   // now my code starts here at this indentation
   const searchParams = ...
}
```

vs

```ts
function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
   // now my code starts here at this indentation
   const searchParams = ...
}
```

As for the regex, maybe something like:

```
^\s*(?:(?:async|export|default|async|public|private|protected) )*function 
```

Test cases:

```
function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
async function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
export function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
export async function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
export default function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
export default async function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
   public function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
   public async function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
   private function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
   private async function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
   protected function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
   protected async function findPets(ownerPartialName: string, type?: PetTypeEnum, lastVisit?: Date, sort: PetSearchSortOrderEnum = PetSearchSortOrderEnum.Ascending, ignoreCache: boolean = false): PetSearchResults {
// This is a comment about a function with a really long declaration.
```

**Comment by yokuze** [comment]
@jthomerson Is it the intention to only target `function` declarations and not method declarations (inside classes where the word `function` will never appear)?

@onebytegone When in TypeScript can you do something like `protected function findPets(..`?

**Comment by onebytegone** [comment]
@yokuze Good point. The function keyword is not always there. The list of test cases, has been updated.

**Comment by lukelafountaine** [comment]
I personally find the single line signature to be more readable. When scanning through a file, I can easily identify a signature when it's on a single line. When it's wrapped, it seems to blend more into the function body. I have also found the wrapped signatures to be annoying while refactoring. For example, there have been times when I removed a parameter from a method and then forgot to reformat the signature to fit on a single line. So, we could end up with multi-line signatures that don't need to be multi-line. 

However, I could go either way. It does seem kind of funny to make an exception just for signatures.

**Review by yokuze — APPROVED** [review]
LGTM!

Just noting that this pattern doesn't account for arrow functions, so wouldn't for cases like this:

```ts
{
   anOption: (a: string, b: number, c: string): void => {

   },
}
```

but that case should be rare, relative to all of the other cases that this pattern _does_ cover.

Longer function declaration lines usually happen when declaring a method on a class or interface, where we fully specify type parameters, scope, and the return type. In the example above, it's usually the case that the type/interface of the option is defined elsewhere, so we can drop the return type and parameter type declarations that make the line lengthy.

**Pull request merged**
